/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adrian_sergio_practica_3ertri_programacion;

import java.awt.Component;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;

/**
 *
 * @author Chevy
 */
public class MatriculasBusquedas extends javax.swing.JFrame {

    /**
     * Creates new form MatriculasBusquedas
     */
    int opcion = 0;
    Utiles util = new Utiles();
    GestionesDeBD bd = new GestionesDeBD();

    public MatriculasBusquedas() {
        initComponents();
        for (Component component : panelAlumno.getComponents()) {
            component.setEnabled(false);
        }
        for (Component component : panelCurso.getComponents()) {
            component.setEnabled(false);
        }
        aceptar.setEnabled(false);

        panelInfo.setText("Por favor, SELECCIONE, BUSCAR CURSO, BUSCAR ALUMNO O MATRICULAR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGA = new javax.swing.JPanel();
        panelEleccion = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonBuscarCurso = new javax.swing.JButton();
        botonBuscarAlumno = new javax.swing.JButton();
        botonMatricular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelInfo = new javax.swing.JTextPane();
        botonCalificar = new javax.swing.JButton();
        textoNota = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        borrarCampos = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        panelAlumno = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cajaListaAlumnos = new javax.swing.JList<>();
        buscarAlumnoInsertado = new javax.swing.JButton();
        textoAlumnos = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        buscarTodos = new javax.swing.JButton();
        panelCurso = new javax.swing.JPanel();
        labelDni = new javax.swing.JLabel();
        buscarCursoInsertado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        cajaListaCursos = new javax.swing.JList<>();
        textoCurso = new javax.swing.JTextField();
        buscarAlumnoInsertado2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGA.setPreferredSize(new java.awt.Dimension(1000, 600));

        panelEleccion.setBackground(new java.awt.Color(56, 49, 64));

        jPanel4.setBackground(new java.awt.Color(202, 199, 215));
        jPanel4.setForeground(new java.awt.Color(138, 134, 4));
        jPanel4.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(202, 199, 215));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(138, 134, 4));
        jLabel1.setText("MATRICULAS Y BUSQUEDAS");
        jLabel1.setAutoscrolls(true);
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        botonBuscarCurso.setBackground(new java.awt.Color(4, 3, 12));
        botonBuscarCurso.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        botonBuscarCurso.setForeground(new java.awt.Color(244, 237, 113));
        botonBuscarCurso.setText("BUSCAR CURSO");
        botonBuscarCurso.setActionCommand("BUSCAR CURSO");
        botonBuscarCurso.setPreferredSize(new java.awt.Dimension(140, 80));
        botonBuscarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarCursoActionPerformed(evt);
            }
        });

        botonBuscarAlumno.setBackground(new java.awt.Color(4, 3, 12));
        botonBuscarAlumno.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        botonBuscarAlumno.setForeground(new java.awt.Color(244, 237, 113));
        botonBuscarAlumno.setText("BUSCAR ALUMNO");
        botonBuscarAlumno.setActionCommand("<html><p>BORRAR</p><p> ALUMNO</p></html>");
        botonBuscarAlumno.setPreferredSize(new java.awt.Dimension(140, 80));
        botonBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarAlumnoActionPerformed(evt);
            }
        });

        botonMatricular.setBackground(new java.awt.Color(4, 3, 12));
        botonMatricular.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        botonMatricular.setForeground(new java.awt.Color(244, 237, 113));
        botonMatricular.setText("MATRICULAR");
        botonMatricular.setPreferredSize(new java.awt.Dimension(140, 80));
        botonMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMatricularActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(panelInfo);

        botonCalificar.setBackground(new java.awt.Color(4, 3, 12));
        botonCalificar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        botonCalificar.setForeground(new java.awt.Color(244, 237, 113));
        botonCalificar.setText("CALIFICAR");
        botonCalificar.setPreferredSize(new java.awt.Dimension(140, 80));
        botonCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalificarActionPerformed(evt);
            }
        });

        textoNota.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        textoNota.setText("NOTA");

        javax.swing.GroupLayout panelEleccionLayout = new javax.swing.GroupLayout(panelEleccion);
        panelEleccion.setLayout(panelEleccionLayout);
        panelEleccionLayout.setHorizontalGroup(
            panelEleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEleccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelEleccionLayout.createSequentialGroup()
                        .addComponent(botonBuscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEleccionLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(panelEleccionLayout.createSequentialGroup()
                        .addComponent(botonMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCalificar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNota, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelEleccionLayout.setVerticalGroup(
            panelEleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEleccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCalificar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNota, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(4, 3, 12));

        aceptar.setBackground(new java.awt.Color(4, 3, 12));
        aceptar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        aceptar.setForeground(new java.awt.Color(244, 237, 113));
        aceptar.setText("HACER GESTION");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        borrarCampos.setBackground(new java.awt.Color(4, 3, 12));
        borrarCampos.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        borrarCampos.setForeground(new java.awt.Color(244, 237, 113));
        borrarCampos.setText("BORRAR TODO");
        borrarCampos.setToolTipText("");
        borrarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarCamposActionPerformed(evt);
            }
        });

        volver.setBackground(new java.awt.Color(4, 3, 12));
        volver.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        volver.setForeground(new java.awt.Color(244, 237, 113));
        volver.setText("VOLVER ATRAS");
        volver.setToolTipText("");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDatos.setBackground(new java.awt.Color(202, 199, 215));

        panelAlumno.setBackground(new java.awt.Color(202, 199, 215));

        jScrollPane3.setViewportView(cajaListaAlumnos);

        buscarAlumnoInsertado.setText("BUSCAR DNI INSERTADO");
        buscarAlumnoInsertado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAlumnoInsertadoActionPerformed(evt);
            }
        });

        textoAlumnos.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        textoAlumnos.setForeground(new java.awt.Color(4, 3, 12));
        textoAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoAlumnosActionPerformed(evt);
            }
        });

        labelNombre.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(4, 3, 12));
        labelNombre.setText("DNI de Alumno:");

        buscarTodos.setText("MOSTRAR TODOS");
        buscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAlumnoLayout = new javax.swing.GroupLayout(panelAlumno);
        panelAlumno.setLayout(panelAlumnoLayout);
        panelAlumnoLayout.setHorizontalGroup(
            panelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlumnoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(textoAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buscarAlumnoInsertado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelAlumnoLayout.createSequentialGroup()
                        .addGroup(panelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(buscarTodos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAlumnoLayout.setVerticalGroup(
            panelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlumnoLayout.createSequentialGroup()
                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarAlumnoInsertado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarTodos)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelCurso.setBackground(new java.awt.Color(202, 199, 215));

        labelDni.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        labelDni.setForeground(new java.awt.Color(4, 3, 12));
        labelDni.setText("Nombre de curso:");

        buscarCursoInsertado.setText("BUSCAR CURSO INSERTADO");
        buscarCursoInsertado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCursoInsertadoActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(cajaListaCursos);

        textoCurso.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        textoCurso.setForeground(new java.awt.Color(4, 3, 12));
        textoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCursoActionPerformed(evt);
            }
        });

        buscarAlumnoInsertado2.setText("MOSTRAR TODOS");
        buscarAlumnoInsertado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAlumnoInsertado2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCursoLayout = new javax.swing.GroupLayout(panelCurso);
        panelCurso.setLayout(panelCursoLayout);
        panelCursoLayout.setHorizontalGroup(
            panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCursoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCursoLayout.createSequentialGroup()
                                .addComponent(labelDni)
                                .addGap(93, 93, 93))
                            .addGroup(panelCursoLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))))
                    .addGroup(panelCursoLayout.createSequentialGroup()
                        .addComponent(textoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCursoLayout.createSequentialGroup()
                        .addComponent(buscarCursoInsertado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCursoLayout.createSequentialGroup()
                        .addComponent(buscarAlumnoInsertado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))))
        );
        panelCursoLayout.setVerticalGroup(
            panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoLayout.createSequentialGroup()
                .addComponent(labelDni, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarCursoInsertado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarAlumnoInsertado2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(panelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout panelGALayout = new javax.swing.GroupLayout(panelGA);
        panelGA.setLayout(panelGALayout);
        panelGALayout.setHorizontalGroup(
            panelGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGALayout.setVerticalGroup(
            panelGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGA, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGA, javax.swing.GroupLayout.PREFERRED_SIZE, 711, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarCursoActionPerformed
        textoCurso.setText("");
        textoAlumnos.setText("");

        for (Component component : panelAlumno.getComponents()) {
            component.setEnabled(false);
        }
        for (Component component : panelCurso.getComponents()) {
            component.setEnabled(true);
        }
        panelInfo.setText("Ponga el nombre del curso o dejelo vacio para ver todos, despues pulse BUSCAR CURSO INSERTADO");
        opcion = 1;

    }//GEN-LAST:event_botonBuscarCursoActionPerformed

    private void botonBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarAlumnoActionPerformed
        textoCurso.setText("");
        textoAlumnos.setText("");
        for (Component component : panelCurso.getComponents()) {
            component.setEnabled(false);
        }

        for (Component component : panelAlumno.getComponents()) {
            component.setEnabled(true);
        }
        panelInfo.setText("Ponga el DNI del Alumno o dejelo vacio para ver todos, despues pulse BUSCAR ALUMNO INSERTADO");

        opcion = 2;
    }//GEN-LAST:event_botonBuscarAlumnoActionPerformed

    private void botonMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMatricularActionPerformed
        textoCurso.setText("");
        textoAlumnos.setText("");
        for (Component component : panelCurso.getComponents()) {
            component.setEnabled(true);
        }

        for (Component component : panelAlumno.getComponents()) {
            component.setEnabled(true);
        }
        String[] datosAlumno;
        datosAlumno = bd.imprimir("*", "ALUMNOS", "DNI", "");
        cajaListaAlumnos.setListData(datosAlumno);
        textoAlumnos.setText("");
        panelInfo.setText("Rellene NOMBRE DE CURSO, DNI DE ALUMNO y pulse HACER GESTION");

        opcion = 1;
        aceptar.setEnabled(true);
    }//GEN-LAST:event_botonMatricularActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        String[] datosAlumno;
        String[] datosCursos;
        boolean cursoEncontrado = false;
        boolean alumnoEncontrado = false;
        String nombreCurso = "";
        String dniAlumno = "";
        panelInfo.setText("");
        if (!util.validarLongitud(textoCurso.getText().trim().toUpperCase(), 1)) {
            System.out.println("Aqui llego");
            panelInfo.setText("Por favor, introduzca un curso que tenga al menos un caracter");
        } else if (!bd.buscar(textoCurso.getText().trim().toUpperCase(), "cursos", "Nombre")) {
            panelInfo.setText("Curso no encontrado, por favor, introduzca uno registrado");
        } else {
            if (bd.buscar(textoCurso.getText().trim().toUpperCase(), "CURSOS", "NOMBRE")) {

                datosCursos = bd.imprimir(textoCurso.getText().trim().toUpperCase(), "CURSOS", "NOMBRE", "");
                panelInfo.setText("CURSO ENCONTRADO");
                cajaListaCursos.setListData(datosCursos);

                int indiceInicio = datosCursos[0].indexOf(":") + 1;
                int indiceFin = datosCursos[0].indexOf("Descripcion", indiceInicio);

                if (indiceInicio != -1 && indiceFin != -1) {
                    nombreCurso = datosCursos[0].substring(indiceInicio, indiceFin).trim();
                    System.out.println("Encontrado " + nombreCurso);
                    cursoEncontrado = true;
                } else {
                    System.out.println("No se encontró ninguna palabra.");
                }
            }
        }
        
        if (!util.validarDNI(textoAlumnos.getText().trim().toUpperCase())) {
            System.out.println("Aqui llego");
            panelInfo.setText(panelInfo.getText() + " " + "Por favor, introduzca un DNI valido 8 numeros y una letra");
        } else if (!bd.buscar(textoAlumnos.getText().trim().toUpperCase(), "ALUMNOS", "dni")) {
            panelInfo.setText(panelInfo.getText() + " " + "DNI no encontrado, por favor, introduzca uno registrado");
        } else {
            if (bd.buscar(textoAlumnos.getText().trim().toUpperCase(), "ALUMNOS", "dni")) {

                datosAlumno = bd.imprimir(textoAlumnos.getText().trim().toUpperCase(), "Alumnos", "dni", "");
                panelInfo.setText(panelInfo.getText() + " " + "ALUMNO ENCONTRADO");
                cajaListaAlumnos.setListData(datosAlumno);

                int indiceInicio = datosAlumno[0].indexOf(":") + 1;
                int indiceFin = datosAlumno[0].indexOf("Nombre", indiceInicio);

                if (indiceInicio != -1 && indiceFin != -1) {
                    dniAlumno = datosAlumno[0].substring(indiceInicio, indiceFin).trim();
                    System.out.println("Encontrado " + dniAlumno);
                    alumnoEncontrado = true;
                } else {
                    System.out.println("No se encontró ninguna palabra.");
                }
            }
        }
        if (opcion == 1) {//MATRICULAR
            if (!bd.existeMatricula("inscripciones", dniAlumno, nombreCurso)) {
                if (alumnoEncontrado && cursoEncontrado) {
                    bd.insertarInscripcion(nombreCurso, dniAlumno);
                    aceptar.setEnabled(false);
                    panelInfo.setText("Se realizó la inscripcion");
                }
            } else {
                panelInfo.setText("El Alumno ya está matriculado en el curso");
            }
        } else if (opcion == 2) {//CALIFICAR
            if (bd.existeMatricula("inscripciones", dniAlumno, nombreCurso)) {
                float nota = util.esNotaValida(textoNota.getText().trim());
                if (nota != -1) {
                    bd.calificar(dniAlumno, nombreCurso, nota);
                    panelInfo.setText("Calificacion realizada");
                } else {
                    panelInfo.setText("Pon una nota valida, < o = que 10 y > o = que 0");
                }
            } else {
                panelInfo.setText("El Alumno no esta matriculado en el curso, selecciona una relacion valida");
            }
        }

    }//GEN-LAST:event_aceptarActionPerformed

    private void borrarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarCamposActionPerformed

        textoCurso.setText("");
        textoAlumnos.setText("");

    }//GEN-LAST:event_borrarCamposActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        PrincipalJFrame principal = new PrincipalJFrame();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void textoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCursoActionPerformed

    private void buscarAlumnoInsertadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAlumnoInsertadoActionPerformed

        String[] datosAlumno = new String[0];
        String[] cursosAlumno = new String[0];
        String[] listaImprimir;
        String imprimir = "";
        if (!util.validarDNI(textoAlumnos.getText().trim().toUpperCase())) {
            System.out.println("Aqui llego");
            panelInfo.setText("Por favor, introduzca un DNI valido 8 numeros y una letra");
        } else if (!bd.buscar(textoAlumnos.getText().trim().toUpperCase(), "ALUMNOS", "dni")) {
            panelInfo.setText("DNI no encontrado, por favor, introduzca uno registrado");
        } else {
            if (bd.buscar(textoAlumnos.getText().trim().toUpperCase(), "ALUMNOS", "dni")) {

                datosAlumno = bd.imprimir(textoAlumnos.getText().trim().toUpperCase(), "Alumnos", "dni", "");
                cursosAlumno = bd.imprimir(textoAlumnos.getText().trim().toUpperCase(), "Inscripciones", "dniAlumno", "nombreCurso");
                panelInfo.setText("ALUMNO ENCONTRADO");
            }
            listaImprimir = new String[datosAlumno.length + cursosAlumno.length + 1];
            listaImprimir[0] = datosAlumno[0];
            listaImprimir[1] = "MATRICULADO EN:";
            for (int i = 0, j = 2; i < cursosAlumno.length; i++, j++) {
                listaImprimir[j] = cursosAlumno[i];
            }
            cajaListaAlumnos.setListData(listaImprimir);

        }


    }//GEN-LAST:event_buscarAlumnoInsertadoActionPerformed

    private void textoAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoAlumnosActionPerformed

    private void buscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTodosActionPerformed
        // TODO add your handling code here:
        String[] datosAlumno;
        datosAlumno = bd.imprimir("*", "ALUMNOS", "DNI", "");
        cajaListaAlumnos.setListData(datosAlumno);
        textoAlumnos.setText("");
    }//GEN-LAST:event_buscarTodosActionPerformed

    private void buscarAlumnoInsertado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAlumnoInsertado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarAlumnoInsertado2ActionPerformed

    private void buscarCursoInsertadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCursoInsertadoActionPerformed
        // TODO add your handling code here:

        String[] datosCursos = new String[1];
        String imprimir = "";
        if (!util.validarLongitud(textoCurso.getText().trim().toUpperCase(), 1)) {
            System.out.println("Aqui llego");
            panelInfo.setText("Por favor, introduzca un curso que tenga al menos un caracter");
        } else if (!bd.buscar(textoCurso.getText().trim().toUpperCase(), "cursos", "Nombre")) {
            panelInfo.setText("Curso no encontrado, por favor, introduzca uno registrado");
        } else {
            if (bd.buscar(textoCurso.getText().trim().toUpperCase(), "CURSOS", "NOMBRE")) {

                datosCursos = bd.imprimir(textoCurso.getText().trim().toUpperCase(), "CURSOS", "NOMBRE", "");
                panelInfo.setText("CURSO ENCONTRADO");
            }

            cajaListaCursos.setListData(datosCursos);

        }


    }//GEN-LAST:event_buscarCursoInsertadoActionPerformed

    private void botonCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalificarActionPerformed
        textoCurso.setText("");
        textoAlumnos.setText("");
        for (Component component : panelCurso.getComponents()) {
            component.setEnabled(true);
        }

        for (Component component : panelAlumno.getComponents()) {
            component.setEnabled(true);
        }

        panelInfo.setText("Escriba el NOMBRE DE CURSO y DNI DE ALUMNO, posteriormente HACER GESTION para hacer la matricula\nSi busca un CURSO o un Alumno aparecerán las inscripciones");

        opcion = 2;
        aceptar.setEnabled(true);
    }//GEN-LAST:event_botonCalificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatriculasBusquedas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatriculasBusquedas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatriculasBusquedas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatriculasBusquedas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton borrarCampos;
    private javax.swing.JButton botonBuscarAlumno;
    private javax.swing.JButton botonBuscarCurso;
    private javax.swing.JButton botonCalificar;
    private javax.swing.JButton botonMatricular;
    private javax.swing.JButton buscarAlumnoInsertado;
    private javax.swing.JButton buscarAlumnoInsertado2;
    private javax.swing.JButton buscarCursoInsertado;
    private javax.swing.JButton buscarTodos;
    private javax.swing.JList<String> cajaListaAlumnos;
    private javax.swing.JList<String> cajaListaCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelDni;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JPanel panelAlumno;
    private javax.swing.JPanel panelCurso;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelEleccion;
    public javax.swing.JPanel panelGA;
    private javax.swing.JTextPane panelInfo;
    private javax.swing.JTextField textoAlumnos;
    private javax.swing.JTextField textoCurso;
    private javax.swing.JTextField textoNota;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
